apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tompeters-site
  labels:
    app: tompeters-site
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
spec:
  rules:
    - host: tompeters.me
      http:
        paths:
          - backend:
              serviceName: tompeters-site
              servicePort: 80
            path: /
  tls:
    - hosts:
        - tompeters.me
      secretName: tls-tompeters
